name: Analyze Plan
description: Analyze terraform plan json

inputs:
  plan-path:
    description: path to analyze terraform plan json
    required: true
  policy-path:
    description: path to protect policy plan yaml
    required: false
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Run summary
      shell: bash
      run: |
        go run ${{ github.action_path }}/app/analyze_plan.go ${{ inputs.plan-path }} ${{ inputs.policy-path }}
